name: Assignment3_CI_9062297_DhruvPatel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nyc311
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium

      - name: Build and run Docker containers
        run: |
          docker compose up -d
          sleep 20  # allow MySQL + Flask containers to initialize

      - name: Run Selenium tests (headless)
        env:
          APP_URL: http://127.0.0.1:5000
        run: |
          echo "Waiting for Flask to start..."
          sleep 10  # extra buffer to ensure app is ready
          pytest -q --maxfail=1 --disable-warnings -v

      - name: Tear down containers
        if: always()
        run: docker compose down
