name: Assignment 3 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Dhruv3008
          MYSQL_DATABASE: nyc311
          MYSQL_USER: dhruv
          MYSQL_PASSWORD: Dhruv3008
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be healthy..."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -h "127.0.0.1" --silent; do
            sleep 5
          done

      - name: Load Database Schema
        run: |
          docker exec -i $(docker ps -qf "name=mysql") mysql -udhruv -pDhruv3008 nyc311 < db/schema.sql

      - name: Run ETL
        run: |
          python etl/etl.py --rows 50 --file data/fixture.csv

      - name: Run Tests
        run: |
          python -m unittest tests/selenium_test.py -v
