name: Assignment-3 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-etl:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Dhruv3008
          MYSQL_DATABASE: nyc311
          MYSQL_USER: dhruv
          MYSQL_PASSWORD: Dhruv3008
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be healthy..."
          for i in {1..30}; do
            mysqladmin ping -hmysql -udhruv -pDhruv3008 && break
            echo "Waiting 2s..."
            sleep 2
          done

      - name: Load schema
        run: |
          mysql -hmysql -udhruv -pDhruv3008 nyc311 < db/schema.sql

      - name: Run ETL with fixture data
        run: |
          export DB_HOST=mysql
          export DB_USER=dhruv
          export DB_PASSWORD=Dhruv3008
          export DB_NAME=nyc311
          python etl/etl.py --rows 50 --file data/fixture.csv

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*_test.py" -v
