name: Assignment 3 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nyc311
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
          echo "Waiting for database..."
          sleep 3
        done

    - name: Load database schema
      run: |
        mysql -h 127.0.0.1 -uroot -proot nyc311 < db/schema.sql

    - name: Run ETL on small fixture CSV
      run: |
        python etl/etl.py --rows 50 --file data/fixture.csv

    - name: Run Selenium tests
      run: |
        pytest -q --disable-warnings tests/selenium_test.py
