name: Assignment 3 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nyc311
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium pymysql pandas python-dotenv

      - name: Wait for MySQL to be healthy
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
            sleep 2
          done

      - name: Load MySQL schema
        run: |
          mysql -h 127.0.0.1 -uroot -proot nyc311 < db/schema.sql

      - name: Run ETL
        run: |
          python etl/etl.py --rows 50  # small fixture CSV for CI

      - name: Start Flask app
        run: |
          nohup python -m flask run --host=0.0.0.0 --port=5000 &

      - name: Run Selenium Tests
        run: |
          python -m unittest tests/selenium_test.py -v
